name: Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify your desired Python version
        
    - name: Install dependencies
      run: pip install poetry 
      run: poetry install --no-interaction
        
    - name: Run pytest
      run: poetry pytest
